services:
  postgres:
    image: postgres:16
    container_name: edu_postgres
    environment:
      POSTGRES_USER: edu_admin
      POSTGRES_PASSWORD: edu_password
      POSTGRES_DB: edu_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: edu_redis
    ports:
      - "6379:6379"

  # auth_service:
  #   build: ./backend/auth
  #   container_name: edu_auth
  #   environment:
  #     DATABASE_URL: postgresql://edu_admin:edu_password@postgres:5432/edu_platform
  #     REDIS_URL: redis://redis:6379/0
  #     SECRET_KEY: "ваш-секретный-ключ-замените"
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   - redis

volumes:
  postgres_data: